#!/bin/bash

function postinstall_sysadmin_ddclient_make_config {
local hostname=$1
local domainname=$2
cat <<EOD
# Configuration file for ddclient generated by debconf
#
# /etc/ddclient.conf

daemon=300
syslog=yes
debug=yes
verbose=yes
force=no
#mail=root
#mail-failure=root
pid=/var/run/ddclient.pid
#----
protocol=dyndns2
use=if, if=wlp2s0, usev6=if, ssl=yes
server=dyn.dns.he.net
login=${hostname}.${domainname}
password='ddns-password-from-HE.NET'
${hostname}.${domainname}
EOD
}

function postinstall_sysadmin_ddclient_config {
  local hostname=$(hostname)
  local domainname=$(hostname -d)
  [[ ! -f /etc/ddclient.conf ]] && postinstall_sysadmin_ddclient_make_config $hostname $domainname > /etc/ddclient.conf
}

function postinstall_sysadmin_ddclient {
  apt-get install ddclient -y
}

postinstall_sysadmin_ddclient_config
postinstall_sysadmin_ddclient
