#!/bin/bash -eu

function __bashrc_bootstrap {
    # make sure python3-pip is installed
    local dir=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))
    local distro="$(${dir}/bin/os_release | cut -d: -f1)"
    case "${distro}" in
        Debian|Ubuntu) dpkg-query -s python3-pip > /dev/null 2>&1 || sudo apt install -y python3-pip;;
        openSUSE)      local v="$(python3 -V | cut -d' ' -f2 | cut -d. -f1-2 | tr -d [.])" ;
                       zypper search -i python${v}-pip > /dev/null 2>&1 || sudo zypper install -y python${v}-pip;;
        *) echo "ERROR: Unsupported distribution" ; return 1;;
    esac


    # make sure python-venv is installed
    case "${distro}" in
        Debian|Ubuntu) dpkg-query -s python3-venv > /dev/null 2>&1 || sudo apt install -y python3-venv;;
        openSUSE) ;;
        *) echo "ERROR: Unsupported distribution" ; return 1;;
    esac
}

__bashrc_bootstrap
